patterns = ['CDLBELTHOLD', 'CDLCLOSINGMARUBOZU', 'CDLDOJI', 'CDLENGULFING',
       'CDLGRAVESTONEDOJI', 'CDLHARAMI', 'CDLHIGHWAVE', 'CDLHIKKAKE',
       'CDLLONGLEGGEDDOJI', 'CDLLONGLINE', 'CDLMARUBOZU', 'CDLRICKSHAWMAN',
       'CDLSHORTLINE', 'CDLSPINNINGTOP']